//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::ARLocation.PlaceAtLocation.ObjectUpdatedEvent))]
	public class PropertyProvider_ARLocation_PlaceAtLocation_ObjectUpdatedEvent : Unity.VisualScripting.SerializedPropertyProvider<ARLocation.PlaceAtLocation.ObjectUpdatedEvent>
	{
	}
}
